### ISSUE TITLE
Proposal Layer Merge Invited

### ISSUE THREAD

**Issue by jinfagang** [huaze555/windows-caffe-faster-rcnn#1]
Hi! I am so glad to see your work, we launched an organization called **UnrealVision**, this is a none-profit org. We maintained a caffe version which includes many layers needed by Computer Vision researchers. I'd like invite you join us and merge the proposal_layer needed by faster-rcnn to [unreal_caffe](https://github.com/UnrealVision/unreal_caffe.git) if you are interested! Wish get your reply.

From UnrealVision.

**Comment by huaze555** [comment]
I'm sorry, because I am going to graduation and have to prepare for graduation thesis, I am afraid no much time, thanks for your invitation.

**Comment by huaze555** [comment]
@jinfagang I'm sorry, because I am going to graduation and have to prepare for graduation thesis, I am afraid no much time, thanks for your invitation.
