### ISSUE TITLE
Unknown layer type: FrcnnRoiData

### ISSUE THREAD

**Issue by freedenS** [huaze555/windows-caffe-faster-rcnn#11]
train_val.protxt文件中输入层的Type为FrcnnRoiData，但caffe.poto中并没有注册这个层，看参数貌似是WindowData，修后会出现Check failed: ExactNumTopBlobs() == top.size() (2 vs. 3) WindowData Layer produces 2 top blob(s) as output的错误，请问您在训练过程中有没有遇到呢？

**Comment by huaze555** [comment]
@freedenS 编译的的时候不会出现这个问题吧。

**Comment by huaze555** [comment]
@freedenS 训练过程也没出现过呀

**Comment by freedenS** [comment]
感谢您的回复哈，我这个caffe不是用的您这个版本，我是编译的vs2015，cuda9.0的环境。
编译的时候不会出现这个问题，训练的时候出现的，使用models/FRCNN/vgg16/train_val.prototxt文件时，
name: "VGG_ILSVRC_16_layers"
#=========Frcnn-RoiData============
layer {
  name: "input-data"
  type: "FrcnnRoiData"
  top: "data"
  top: "im_info"
  top: "gt_boxes"
  include {
    phase: TRAIN
  }
  window_data_param {
    source: "examples/FRCNN/dataset/voc2007.trainval"
    config: "examples/FRCNN/config/voc_config.json"
    root_folder: "VOCdevkit/VOC2007/JPEGImages/"
    cache_images: true
  }
}
发现输入层的type是FrcnnRoiData。
训练方法是按照您的examples/FRCNN/vgg16/train_frcnn.bat
从solver.prototxt调用网络的这行train_net: "models/FRCNN/vgg16/train_val.proto"应该是train_val.prototxt吧？

**Comment by huaze555** [comment]
@freedenS 你如果要使用FrcnnRoiData层，就要编译我的这个版本的代码，或者你把FrcnnRoiData层的相关文件都添加进你的caffe版本里再编译，不过这是一个很复杂的工作。如果你的版本不支持的话，你直接用，肯定会出问题的。

**Comment by freedenS** [comment]
@huaze555 谢谢，刚去看了下linux版本的确实是有FrcnnRoiData层的相关文件，之前只是单纯检查了caffe.proto，我这环境不好变更，只能按照您的教程尝试自己编译下了，感谢您的教程^_^
