### ISSUE TITLE
博主你好，数据怎么生成呢？跟linux下的不一样，还需要jason文件，多谢啦

### ISSUE THREAD

**Issue by zjz5250** [huaze555/windows-caffe-faster-rcnn#9]

**Comment by huaze555** [comment]
@zjz5250 python版的训练数据是xml格式的，这个版本训练数据是txt形式的。你按照格式要求，用任意语言制作数据集就好了。

**Comment by zjz5250** [comment]
谢谢啦





新浪邮箱客户端

------------------------原始邮件------------------------
发件人：huaze555<notifications@github.com>
时间：2018年8月31日 17:51:05
收件人：huaze555/windows-caffe-faster-rcnn<windows-caffe-faster-rcnn@noreply.github.com>
抄送：phil<zjz5250@sina.cn>,Mention<mention@noreply.github.com>
主题：Re: [huaze555/windows-caffe-faster-rcnn] 博主你好，数据怎么生成呢？跟linux下的不一样，还需要jason文件，多谢啦 (#9)

@zjz5250(https://github.com/zjz5250)python版的训练数据是xml格式的，这个版本训练数据是txt形式的。你按照格式要求，用任意语言制作数据集就好了。
